# Generated by Django 5.1.5 on 2025-02-28 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='fooditems',
            name='created_date',
        ),
        migrations.AddField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-02-28 08:10:10'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-02-28 08:10:10'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fooditems',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-02-28 08:10:10'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-02-28 08:10:10'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='created_by',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='updated_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='updated_date',
            field=models.DateTimeField(default='2025-02-28 08:10:10'),
            preserve_default=False,
        ),
    ]
