# Generated by Django 5.1.5 on 2025-02-28 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0002_remove_cart_created_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='fooditems',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='fooditems',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='updated_by',
        ),
    ]
