# Generated by Django 5.1.5 on 2025-02-28 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0003_remove_cart_created_by_remove_cart_updated_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='cart',
            name='created_by',
            field=models.CharField(default='kannan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='updated_by',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='created_by',
            field=models.CharField(default='kannan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='updated_by',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='fooditems',
            name='created_by',
            field=models.CharField(default='kannan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fooditems',
            name='updated_by',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='created_by',
            field=models.CharField(default='kannan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='updated_by',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='created_by',
            field=models.CharField(default='kannan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='updated_by',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='updated_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='updated_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='fooditems',
            name='updated_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='updated_date',
            field=models.DateTimeField(null=True),
        ),
    ]
