# Generated by Django 5.1.5 on 2025-03-01 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0004_remove_order_updated_at_cart_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='price',
            field=models.FloatField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
