# Generated by Django 5.1.5 on 2025-04-13 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0005_cart_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_no',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
