# Generated by Django 5.1.5 on 2025-05-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0006_order_address_order_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone_no',
            field=models.CharField(max_length=20),
        ),
    ]
