# Generated by Django 5.1.5 on 2025-05-11 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0008_order_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='customer',
        ),
    ]
